POST http://localhost:5000/api/auth/register
Content-Type: application/json

{
    "name": "test",
    "email": "test@test.com",
    "password": "tes45%%TYiop88*h"
}

###

POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
    "email": "test@test.com",
    "password": "tes45%%TYiop88*h"
}
