POST http://localhost:5000/api/auth/register
Content-Type: application/json

{
    "name": "testSSS",
    "email": "testSSS@test.com",
    "password": "777***huyuiopSSS"
}

###

POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
    "email": "testSSS@test.com",
    "password": "777***huyuiopSSS"
}

###
GET http://localhost:5000/api/auth/user/6592e8fc1d91a6b414ce87f3


###
POST http://localhost:5000/api/auth/logout/

###
DELETE http://localhost:5000/api/auth/user/6592e8fc1d91a6b414ce87f3


